- name: Install Multiple Software on Windows
  hosts: windows
  tasks:
    - name: Download Google Chrome Installer
      win_get_url:
        url: "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
        dest: "C:\\Windows\\Temp\\chrome_installer.exe"

    - name: Install Google Chrome
      win_package:
        path: "C:\\Windows\\Temp\\chrome_installer.exe"
        arguments: "/silent /install"
        state: present

    - name: Download Notepad++ Installer
      win_get_url:
        url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.5.8/npp.8.5.8.Installer.x64.exe"
        dest: "C:\\Windows\\Temp\\notepadpp_installer.exe"

    - name: Install Notepad++
      win_package:
        path: "C:\\Windows\\Temp\\notepadpp_installer.exe"
        arguments: "/S"
        state: present
